apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::800917983494:user/paulotoro
      username: paulotoro
      groups:
        - system:masters  # Grants full admin access (use cautiously!)